// console.log("Throw catch finally");
// //try: tests the block of code
// //catch: handle the error
// //throw: create custom error
// //finally: executes code after throw catch , no matter what

// //below example : alert is misspelled
// try {
//   addlert("hello World");
// } catch (err) {
//   console.log(err); //addlert is not defined
// }

// // //JS creates error object with name and message properties
// // let text = "";
// // try{
// //     if (text == "") throw "empty string";
// //     if (isNaN(x)) throw "Not a Number";
// // }
